Repository thoth-station/package-extract, pull requests merged in 2018-08, with the labels that each got.

#111 Automatic update of dependency pylint from 2.0.1 to 2.1.0
  Pipfile.lock
Labels: bot

#110 Fix missing/extra parameters in template
  openshift/pod-template.yaml
Labels: approved, size/M

#113 Automatic update of dependency pytest from 3.7.0 to 3.7.1
  Pipfile.lock
Labels: bot

#116 Automatic update of dependency pylint from 2.1.0 to 2.1.1
  Pipfile.lock
Labels: bot

#120 Automatic update of dependency pytest-timeout from 1.3.1 to 1.3.2
  Pipfile.lock
Labels: bot

#119 Automatic update of dependency pytest from 3.7.1 to 3.7.3
  Pipfile.lock
Labels: bot

#121 Recover from non-fatal errors during image extraction
  thoth/package_extract/image.py
Labels: size/XS

#123 Use common logging to unify configuration in the cluster
  thoth/package_extract/cli.py
Labels: approved, size/M

#124 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#122 Add support for debian-based packages
  Dockerfile
  openshift/pod-template.yaml
  thoth/package_extract/image.py
Labels: approved, size/L

#126 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency pytest from 3.7.3 to 3.7.4
  Pipfile.lock
Labels: bot

#129 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot
