Repository thoth-station/package-extract, pull requests merged in 2018-06, with the labels that each got.

#40 this is to test zuul
  .flake8
  .zuul.yaml
Labels: approved, size/S

#30 Update README file
  README.rst
  thoth/package_extract/cli.py
Labels: size/XXL

#39 Automatic update of dependency pytest from 3.6.0 to 3.6.1
  Pipfile.lock
Labels: approved, bot, size/XS

#31 Update core.py
  thoth/package_extract/core.py
Labels: approved, size/S

#42 Automatic update of dependency thoth-common from 0.0.6 to 0.0.7
  Pipfile.lock
Labels: approved, bot, size/XS

#47 cleaning linter errors out
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#52 Exclude .rst files from coala linecounter checks
  .coafile
Labels: approved, size/XS

#51 fixing coala errors/warnings
  thoth/package_extract/core.py
Labels: approved, size/S

#54 Automatic update of dependency pylint from 1.9.1 to 1.9.2
  Pipfile.lock
Labels: approved, bot, size/XS

#53 added git hooks for pre commit checks
  .git_init/hooks/pre-commit
  .git_init/hooks/pre-push
Labels: approved, size/S

#56 Automatic update of dependency pytest-timeout from 1.2.1 to 1.3.0
  Pipfile.lock
Labels: bot, size/XS

#64 Automatic update of dependency thoth-analyzer from 0.0.5 to 0.0.6
  Pipfile.lock
Labels: bot, size/S

#65 Automatic update of dependency thoth-common from 0.0.7 to 0.0.8
  Pipfile.lock
Labels: bot, size/XS

#66 Automatic update of dependency pytest from 3.6.1 to 3.6.2
  Pipfile.lock
Labels: bot, size/S
