Repository thoth-station/package-extract, pull requests merged in 2018-04, with the labels that each got.

#7 Respect transition to a custom org
  setup.py
Labels: approved

#9 Introduce --no-tls-verify flag
  thoth/package_extract/cli.py
  thoth/package_extract/core.py
  thoth/package_extract/image.py
Labels: approved

#12 License and license headers
  LICENSE
  setup.py
  test/case.py
  test/handlers/test_base.py
  test/handlers/test_dnf.py
  test/handlers/test_pip.py
  test/handlers/test_pip3.py
  test/handlers/test_yum.py
  test/test_core.py
  thoth/package_extract/cli.py
  thoth/package_extract/core.py
  thoth/package_extract/exceptions.py
  thoth/package_extract/handlers/base.py
  thoth/package_extract/handlers/dnf.py
  thoth/package_extract/handlers/pip.py
  thoth/package_extract/handlers/pip3.py
  thoth/package_extract/handlers/yum.py
  thoth/package_extract/image.py
  thoth/package_extract/koji.py
Labels: approved, size/XL

#14 updated .gitignore and set the trove category to the right copyright
  .gitignore
  setup.py
Labels: approved, size/L
