Repository thoth-station/package-extract, pull requests merged in 2018-09, with the labels that each got.

#132 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#133 Automatic update of dependency pytest-cov from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot

#135 Automatic update of dependency thoth-common from 0.2.7 to 0.3.0
  Pipfile.lock
Labels: bot

#136 Automatic update of dependency pytest from 3.7.4 to 3.8.0
  Pipfile.lock
Labels: bot

#134 Increase image analysis timeout
  openshift/pod-template.yaml
Labels: approved, size/XS

#137 Feature/little cleanup
  .coafile
  .zuul.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
Labels: size/XL

#139 Automatic update of dependency thoth-common from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency pytest from 3.8.0 to 3.8.1
  Pipfile.lock
Labels: bot

#141 Automatic update of dependency click from 6.7 to 7.0
  Pipfile.lock
Labels: bot

#142 Automatic update of dependency thoth-common from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot

#143 Automatic update of dependency thoth-common from 0.3.2 to 0.3.5
  Pipfile.lock
Labels: bot

#144 Automatic update of dependency thoth-common from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot
