Repository thoth-station/package-extract, pull requests merged in 2018-07, with the labels that each got.

#70 /usr/bin/python3 is being removed
  setup.py
Labels: approved, size/XS

#73 Remove pydocstyle from direct dev requirements
  Pipfile
Labels: approved

#76 Automatic dependency re-locking
  Pipfile.lock
Labels: bot

#79 Automatic dependency re-locking
  Pipfile.lock
Labels: bot

#80 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#83 Initial dependency lock
  Pipfile.lock
Labels: bot

#84 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#85 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#68 Update core.py
  thoth/package_extract/core.py
Labels: approved, size/XS

#89 Automatic update of dependency pylint from 1.9.2 to 2.0.0
  Pipfile.lock
Labels: bot

#91 Automatic update of dependency daiquiri from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: bot

#93 Fix missing sources during image build
  Dockerfile
Labels: approved

#94 Automatic update of dependency daiquiri from 1.4.0 to 1.5.0
  Pipfile.lock
Labels: bot

#92 Introduce pod template
  openshift/pod-template.yaml
Labels: approved

#96 Automatic update of dependency pylint from 2.0.0 to 2.0.1
  Pipfile.lock
Labels: bot

#97 Automatic update of dependency pytest-timeout from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: bot

#98 Adjust template labels
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/pod-template.yaml
Labels: approved

#99 Remove base image
  Dockerfile
  Dockerfile-base.fedora
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#100 Package extraction is not a job
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#104 Add missing dependency - prometheus-client
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved

#105 Increase CPU as builds take too much time
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#107 Automatic update of dependency prometheus-client from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#108 Be consistent with label naming
  openshift/pod-template.yaml
Labels: approved, size/XS

#109 Automatic update of dependency pytest from 3.6.4 to 3.7.0
  Pipfile.lock
Labels: bot
