Repository thoth-station/package-extract, pull requests merged in 2019-12, with the labels that each got.

#305 Dereference link to Python binary in Python discovery part
  Pipfile.lock
  thoth/package_extract/image.py
Labels: approved, size/M

#324 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#326 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/S

#325 Change Sphinx theme
  docs/source/conf.py
Labels: approved, size/XS

#327 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/S

#328 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#330 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
Labels: approved, size/S

#331 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#332 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#307 Find cuda version
  thoth/package_extract/image.py
Labels: size/M, size/S

#333 Adjust requests due to OOM
  openshift/job-template.yaml
Labels: approved

#334 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/S

#335 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS

#337 Automatic update of dependency daiquiri from 1.6.0 to 1.6.1
  Pipfile.lock
Labels: bot, size/M
