Repository thoth-station/package-extract, pull requests merged in 2019-11, with the labels that each got.

#310 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#311 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#312 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/XS

#313 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#314 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#316 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#320 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#318 Propagate document id into job
  openshift/job-template.yaml
Labels: approved, size/XS

#321 Automatic update of dependency thoth-common from 0.9.17 to 0.9.18
  Pipfile.lock
Labels: bot, size/XS

#323 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS

#322 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/XS
