Repository thoth-station/package-extract, pull requests merged in 2019-03, with the labels that each got.

#221 Automatic update of dependency attrs from 18.2.0 to 19.1.0
  Pipfile.lock
Labels: bot

#223 Use Sphinx for documentation
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L

#225 Provide metadata parameter in template
  openshift/job-template.yaml
Labels: size/XS

#226 Do not scan autogenerated conf.py from Sphinx by coala
  .coafile
Labels: size/XS

#224 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#222 Automatic update of dependency pytest from 4.3.0 to 4.3.1
  Pipfile.lock
Labels: bot

#228 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#229 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
