Repository thoth-station/package-extract, pull requests merged in 2019-08, with the labels that each got.

#272 Add subprocess
  thoth/package_extract/image.py
Labels: approved, size/XS

#270 Minor rework of system symbols gathering
  thoth/package_extract/image.py
Labels: approved, size/L

#273 Delete not used import
  thoth/package_extract/image.py
Labels: approved, size/XS

#274 Automatic update of dependency daiquiri from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot

#275 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#276 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#277 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#278 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#280 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#281 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
