Repository thoth-station/package-extract, pull requests merged in 2019-02, with the labels that each got.

#210 Update year in sources
  test/case.py
  test/handlers/test_base.py
  test/handlers/test_dnf.py
  test/handlers/test_pip.py
  test/handlers/test_pip3.py
  test/handlers/test_yum.py
  test/test_core.py
  thoth/package_extract/cli.py
  thoth/package_extract/core.py
  thoth/package_extract/exceptions.py
  thoth/package_extract/handlers/base.py
  thoth/package_extract/handlers/dnf.py
  thoth/package_extract/handlers/pip.py
  thoth/package_extract/handlers/pip3.py
  thoth/package_extract/handlers/yum.py
  thoth/package_extract/image.py
Labels: size/M

#209 Automatic update of dependency pytest from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#211 Automatic update of dependency pytest from 4.2.0 to 4.2.1
  Pipfile.lock
Labels: bot

#213 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#214 Automatic update of dependency thoth-analyzer from 0.1.0 to 0.1.2
  Pipfile.lock
Labels: bot

#216 Add metadata which are propagated in Thoth deployment
  thoth/package_extract/__init__.py
  thoth/package_extract/cli.py
  thoth/package_extract/core.py
  thoth/package_extract/handlers/base.py
  thoth/package_extract/handlers/pip3.py
  thoth/package_extract/handlers/yum.py
  thoth/package_extract/image.py
  thoth/package_extract/rpmlib.py
Labels: size/S, size/XL

#220 Fix Coala errors
  thoth/package_extract/handlers/pip3.py
  thoth/package_extract/image.py
Labels: size/S

#217 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#218 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot
