Repository thoth-station/package-extract, pull requests merged in 2019-10, with the labels that each got.

#291 Automatic update of dependency attrs from 19.1.0 to 19.2.0
  Pipfile.lock
Labels: bot

#292 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#290 [WIP] Add default python version
  thoth/package_extract/image.py
Labels: approved, size/M, size/S, size/XS, work-in-progress

#293 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#295 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#296 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#297 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#294 Get python version for interpreters
  thoth/package_extract/image.py
Labels: approved, size/M, size/S

#298 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#299 Automatic update of dependency attrs from 19.2.0 to 19.3.0
  Pipfile.lock
Labels: bot

#303 Capture container image size
  thoth/package_extract/core.py
  thoth/package_extract/image.py
Labels: approved, size/S

#304 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#306 updated templates with annotations
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/S
