Repository thoth-station/package-extract, pull requests merged in 2019-07, with the labels that each got.

#255 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#257 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#256 finding checksums for all .py files
  thoth/package_extract/image.py
Labels: approved, size/M, size/S

#259 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#262 Add CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/XS

#261 Fix logger name in an installed package
  thoth/package_extract/cli.py
Labels: approved, size/XS

#260 Gather information about operating system
  thoth/package_extract/image.py
Labels: size/M

#263 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#266 Automatic update of dependency thoth-common from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#267 Add code to get system symbols
  Dockerfile
  Pipfile
  Pipfile.lock
  thoth/package_extract/image.py
Labels: approved, size/L, size/M, size/XL
