Repository thoth-station/package-extract, pull requests merged in 2019-05, with the labels that each got.

#236 Automatic update of dependency pytest-cov from 2.6.1 to 2.7.1
  Pipfile.lock
Labels: bot

#237 Minor fix to display correct release in title of docs html
  setup.py
Labels: approved, size/XS

#238 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#240 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#241 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#242 fix template for thoth common requirement
  openshift/job-template.yaml
Labels: approved, size/XS

#243 Add support for v1 container image format
  thoth/package_extract/image.py
Labels: approved, size/S
