Repository thoth-station/package-extract, pull requests merged in 2020-11, with the labels that each got.

#425 port to python 38
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#427 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#429 update aicoe-ci configuration for package-extract
  .aicoe-ci.yaml
Labels: size/S
