Repository thoth-station/package-extract, pull requests merged in 2020-07, with the labels that each got.

#405 [WIP]migrate to pre-commit
  .coafile
  .flake8
  .git_init/hooks/pre-commit
  .git_init/hooks/pre-push
  .github/CODEOWNERS
  .pre-commit-config.yaml
  Pipfile
  README.rst
  coala_requirements.txt
  docs/source/conf.py
  setup.py
  test/case.py
  test/data/pip3/input/fc26_install_celery.txt
  test/data/pip3/input/fc26_install_click.txt
  test/data/pip3/input/fc26_install_daiquiri.txt
  test/data/pip3/input/fc26_install_flask.txt
  test/data/pip3/input/fc26_install_pytorch.txt
  test/data/pip3/input/fc26_install_tensorflow.txt
  test/data/pip3/input/fc26_install_tensorflow_gpu.txt
  test/data/yum/input/centos7_upgrade_and_install.txt
  test/data/yum/input/fc27_ugrade_and_install.txt
  test/data/yum/output/centos7_upgrade_and_install.txt.json
  test/handlers/__init__.py
  test/handlers/test_base.py
  test/handlers/test_dnf.py
  test/handlers/test_pip.py
  test/handlers/test_pip3.py
  test/handlers/test_yum.py
  test/test_core.py
  thoth/package_extract/__init__.py
  thoth/package_extract/core.py
  thoth/package_extract/handlers/__init__.py
  thoth/package_extract/image.py
Labels: approved, size/XXL

#416 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/M

#418 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#419 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#420 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/M
