Repository thoth-station/package-extract, pull requests merged in 2020-06, with the labels that each got.

#404 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/M

#406 migrate OpenShift templates to thoth-application
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/L

#407 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot

#408 Automatic update of dependency thoth-common from 0.13.8 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/L

#409 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: approved, bot, size/L

#411 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot, size/L
