Repository thoth-station/package-extract, pull requests merged in 2020-01, with the labels that each got.

#339 Mark package-extract pods for cleanup
  openshift/job-template.yaml
Labels: approved, size/XS

#340 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/L

#341 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#342 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#343 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/M

#344 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#338 Happy new year!
  docs/source/conf.py
  test/case.py
  test/handlers/test_base.py
  test/handlers/test_dnf.py
  test/handlers/test_pip.py
  test/handlers/test_pip3.py
  test/handlers/test_yum.py
  test/test_core.py
  thoth/package_extract/cli.py
  thoth/package_extract/core.py
  thoth/package_extract/exceptions.py
  thoth/package_extract/handlers/base.py
  thoth/package_extract/handlers/dnf.py
  thoth/package_extract/handlers/pip.py
  thoth/package_extract/handlers/pip3.py
  thoth/package_extract/handlers/yum.py
  thoth/package_extract/image.py
Labels: approved, size/M

#345 Automatic update of dependency daiquiri from 1.6.1 to 2.0.0
  Pipfile.lock
Labels: bot, size/M

#346 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/XS

#347 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/XS

#348 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#349 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#351 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#352 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#353 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#354 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#355 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#356 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/S

#357 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
