Repository thoth-station/package-extract, pull requests merged in 2022-01, with the labels that each got.

#460 add kebechet to crossroads in docs
  docs/source/index.rst
Labels: approved, size/XS

#465 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#467 Remove unused .thothTemplate.yaml
  .thothTemplate.yaml
Labels: approved, size/S

#468 Remove colon from the runtime environment name
  .thoth.yaml
Labels: approved, lgtm, size/XS
